@startuml
    package obfuscating {

        class Obfuscator {
            -String code
            -List<Mangler> manglers

            +Obfuscator()
            +String obfuscateCode(String code, 
                \tProperties obfuscatingOptions)
        }

        interface Mangler {
            +void mangle(JSONObject codeSyntaxTree)
        }

        class ConstantPruner implements Mangler
        class TextEncoder implements Mangler
        class NumberEncoder implements Mangler
        class LoopMangler implements Mangler
        class ConditionMangler implements Mangler
        
        Obfuscator "1" o- "0..*" Mangler
    }

    package forms {
        class MainForm {
            -Obfuscator obfuscator
        }
    }

    MainForm "1" o-- "1" Obfuscator
@enduml